sudo: required
services:
  - docker

before_install:
  - docker build -t rahuldaware1991/docker-react -f Dockerfile.dev .

script:
  - docker run rahuldaware1991/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-134760815083"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_ACCESS_PASSWORD"